# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'OpenCVTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenCVTest

  pod "OpenCV", '~>3.4.2'

end
